export type ApexPlatform = 'PC' | 'PS4' | 'X1';
export type CurrentLegends =
    | 'Revenant'
    | 'Crypto'
    | 'Horizon'
    | 'Gibraltar'
    | 'Wattson'
    | 'Fuse'
    | 'Bangalore'
    | 'Wraith'
    | 'Octane'
    | 'Bloodhound'
    | 'Caustic'
    | 'Lifeline'
    | 'Pathfinder'
    | 'Loba'
    | 'Mirage'
    | 'Rampart'
    | 'Valkyrie'
    | 'Seer'
    | 'Ash';
