import { MessageEmbed } from 'discord.js';
import { SlashCommand } from '../../Structures/Interfaces';
import { GetQuote } from '../../Modules/APIs/Quote';

export const slashCommand: SlashCommand = {
    name: 'quote',
    description: 'Sends a quote generated by an AI',
    type: 'CHAT_INPUT',
    async run(client, interaction, options, data) {
        const quote = await GetQuote();

        if (!quote) interaction.followUp({ embeds: [new MessageEmbed().setColor(client.config.color).setTitle('API Unavailable.')] });

        const embed = new MessageEmbed()
            .setColor(client.config.color)
            .setFooter(client.config.embed_footer)
            .setTitle('An AI-Generated Quote')
            .setURL('https://inspirobot.me')
            .setImage(quote);

        interaction.followUp({ embeds: [embed] });
    }
}
